apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demosite-home-ff1-dev
  namespace: demo-website
spec:
  secretName: demosite-home-ff1-dev-prod-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - demosite.home.ff1.dev
