apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-home-ff1-dev
  namespace: traefik
spec:
  secretName: traefik-home-ff1-dev-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - traefik.home.ff1.dev
